Settings:
  kick:
    message: "&3%group% %player% wyrzuci\u0139\u201a %target% za %message%"
  ban:
    message: "&3%group% %player% zbanowa\u0139\u201a %target% za %message%"
  warn:
    message: "&3dosta\u0139\u201aes ostrzezenie za %message%"
  mute:
    message: "&3zosta\u0139\u201aes wyciszony %message%"
Stoniarka:
  name: '&2Stoniarka'
  place_message: Postawiono
  break_message: zniszczono
  lore:
    - lore 1
    - lore 2
drop:
  cobble_name: '&7Cobblestone drop'
  cobble_slot: 35
  name: '&5Drop'
  size: 4
  DIAMOND:
    name: '&bDiamond'
    chance: 10
    inventory_slot: 10
    inventory_lore:
      - '&5Szansa 10'
  EMERALD:
    name: '&aEmerald'
    chance: 10
    inventory_slot: 11
    inventory_lore:
      - '&5Szansa 10'
  REDSTONE:
    name: '&4Redstone'
    chance: 10
    inventory_slot: 12
    inventory_lore:
      - '&5Szansa 15'
  IRON_INGOT:
    name: '&6Iron'
    chance: 15
    inventory_slot: 13
    inventory_lore:
      - '&5Szansa 15'
  ENDER_PEARL:
    name: '&3Ender pearl'
    chance: 5
    inventory_slot: 14
    inventory_lore:
      - '&5Szansa 5'
  GOLD_INGOT:
    name: '&eGold ingot'
    chance: 10
    inventory_slot: 15
    inventory_lore:
      - '&5Szansa 10'
case:
  start:
    name_Inventory: '&3Skrzynia'
    material_chest: CHEST
    name_chest: '&4Skrzynia test'
    lore_chest:
      - '&6opis'
      - '&8skrzyni'
    name_key: '&8klucz test'
    lore_key:
      - '&6opis'
      - '&8klucza'
    items:
      '1':
        material: CHEST
        name: "\xa74Skrzynia test"
        ilosc: '1'
        metadata: 0
        lore:
          - "\xa76opis"
          - "\xa78skrzyni"
        enchants: []
      '2':
        material: DIAMOND_SWORD
        name: "\xa75test24323"
        ilosc: '2'
        metadata: 0
        lore:
          - "\xa74t234est"
        enchants:
          - FIRE_ASPECT#2
          - DURABILITY#1
      '3':
        material: ANVIL
        ilosc: '64'
        metadata: 0
        enchants: []
kits:
  startowy:
    Delay: 5
    Permission: mdrop.startowy
    items:
      '1':
        material: CHEST
        name: "\xa74Skrzynia test"
        ilosc: '1'
        metadata: 0
        lore:
          - "\xa76opis"
          - "\xa78skrzyni"
        enchants: []
  test:
    Delay: 300
    Permission: mdrop.test
    items:
      '1':
        material: LEAVES
        ilosc: '1'
        metadata: 0
        enchants: []
      '2':
        material: STONE_SWORD
        ilosc: '3'
        metadata: 0
        enchants: []
      '3':
        material: TNT
        name: "\xa7cOdpalone TNT"
        ilosc: '3'
        metadata: 0
        enchants: []
      '4':
        material: ENDER_PORTAL_FRAME
        name: "\xa7eSandFarmer"
        ilosc: '1'
        metadata: 0
        enchants: []
      '5':
        material: DIAMOND_SWORD
        ilosc: '1'
        metadata: 0
        enchants:
          - DAMAGE_ALL#3
