name: MDrop
version: '${project.version}'
main: pl.rex89m.mdrop.MDrop
load: STARTUP
authors: [ rex89m ]
depend:
  - Essentials
commands:
  open:
  case:
  topcase:
  stoniarka:
  drop:
  efekty:
  kit:
  additem:
  crafting:
  kick:
  ban:
  warn:
  mute:
  unban:
  unmute:
  otchlan:
  createkit: