name: MDrop
version: '${project.version}'
main: pl.rex89m.mdrop.MDrop
load: STARTUP
authors: [ rex89m ]
depend:
  - BossBarAPI
  - Essentials
commands:
  open:
  case:
  topcase:
  stoniarka:
  drop:
  efekty:
  kit: